- app/views/layouts/application.html.erb
> [test]コンフリクト実験

- app/views/layouts/application.html.erb
> [Add]コンフリクト

- Gemfile
- Gemfile.lock
- app/javascript/packs/application.js
- app/javascript/stylesheets/application.scss
- app/views/layouts/application.html.erb
- config/webpack/environment.js
- package.json
- yarn.lock
bootstrap,fontawesom,enum,pry-byebugを導入しました。
> [add]gem-install

- db/migrate/20220516081024_change_to_column_default_to_customers.rb
- db/schema.rb
is_deletedのデフォルト値をfalseに変更しました。
> [add] is_deleted change

- app/models/product.rb
- db/migrate/20220516074603_create_products.rb
- db/schema.rb
- test/fixtures/products.yml
- test/models/product_test.rb
Productモデル作成しました。
コントローラーはまだです。
> [add]Productモデル作成

- app/models/order.rb
- app/models/order_product.rb
- db/migrate/20220516083525_create_orders.rb
- db/migrate/20220516084049_create_order_products.rb
- db/schema.rb
- test/fixtures/order_products.yml
- test/fixtures/orders.yml
- test/models/order_product_test.rb
- test/models/order_test.rb
orderとorderproductのモデルを作成しました。
> [add]Order OrderProduct model

- app/models/cart_product.rb
- app/models/genre.rb
- app/models/shipping_address.rb
- db/migrate/20220516094802_create_cart_products.rb
- db/migrate/20220516095023_create_genres.rb
- db/migrate/20220516095204_create_shipping_addresses.rb
- db/schema.rb
- test/fixtures/cart_products.yml
- test/fixtures/genres.yml
- test/fixtures/shipping_addresses.yml
- test/models/cart_product_test.rb
- test/models/genre_test.rb
- test/models/shipping_address_test.rb
> [finish]add model

- app/models/customer.rb
> [add]migrateしました

- app/assets/stylesheets/admin/orders.scss
- app/assets/stylesheets/admin/products.scss
- app/controllers/admin/orders_controller.rb
- app/controllers/admin/products_controller.rb
- app/helpers/admin/orders_helper.rb
- app/helpers/admin/products_helper.rb
- app/views/admin/orders/show.html.erb
- app/views/admin/products/edit.html.erb
- app/views/admin/products/index.html.erb
- app/views/admin/products/new.html.erb
- app/views/admin/products/show.html.erb
- config/routes.rb
- test/controllers/admin/orders_controller_test.rb
- test/controllers/admin/products_controller_test.rb
> [add]controller みさ

- app/assets/stylesheets/admin/genres.scss
- app/assets/stylesheets/public/customers.scss
- app/controllers/admin/genres_controller.rb
- app/controllers/public/customers_controller.rb
- app/helpers/admin/genres_helper.rb
- app/helpers/public/customers_helper.rb
- app/views/admin/genres/create.html.erb
- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
- app/views/admin/genres/update.html.erb
- app/views/public/customers/edit.html.erb
- app/views/public/customers/show.html.erb
- app/views/public/customers/update.html.erb
- config/routes.rb
- test/controllers/admin/genres_controller_test.rb
- test/controllers/public/customers_controller_test.rb
> [add]controllerよっしー

- app/assets/stylesheets/admin/customers.scss
- app/assets/stylesheets/public/orders.scss
- app/controllers/admin/customers_controller.rb
- app/controllers/public/orders_controller.rb
- app/helpers/admin/customers_helper.rb
- app/helpers/public/orders_helper.rb
- app/views/admin/customers/edit.html.erb
- app/views/admin/customers/index.html.erb
- app/views/admin/customers/show.html.erb
- app/views/public/orders/complete.html.erb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/index.html.erb
- app/views/public/orders/new.html.erb
- app/views/public/orders/show.html.erb
- config/routes.rb
- test/controllers/admin/customers_controller_test.rb
- test/controllers/public/orders_controller_test.rb
> [add]controllerふくちゃん

- app/assets/stylesheets/admin/homes.scss
- app/assets/stylesheets/public/homes.scss
- app/assets/stylesheets/public/products.scss
- app/controllers/admin/homes_controller.rb
- app/controllers/public/homes_controller.rb
- app/controllers/public/products_controller.rb
- app/helpers/admin/homes_helper.rb
- app/helpers/public/homes_helper.rb
- app/helpers/public/products_helper.rb
- app/views/admin/homes/top.html.erb
- app/views/public/homes/about.html.erb
- app/views/public/homes/top.html.erb
- app/views/public/products/index.html.erb
- app/views/public/products/show.html.erb
- config/routes.rb
- test/controllers/admin/homes_controller_test.rb
- test/controllers/public/homes_controller_test.rb
- test/controllers/public/products_controller_test.rb
> add_controller　くーろん

- app/controllers/application_controller.rb
- app/views/layouts/application.html.erb
> [add]log_out追加

- app/controllers/admin/genres_controller.rb
- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
ジャンル index,showビュー編集
ジャンル コントローラー編集
> [add] gernre index,show.hrml controller編集

- app/controllers/admin/products_controller.rb
- app/views/admin/products/new.html.erb
- app/views/admin/products/show.html.erb
admin/products show new controllerを追加しました
> [add]admin/products new show controller

- app/controllers/admin/customers_controller.rb
- app/views/admin/customers/edit.html.erb
- app/views/admin/customers/index.html.erb
- app/views/admin/customers/show.html.erb
> [add]admin/customer変更

- app/models/product.rb
- app/views/public/products/index.html.erb
- app/views/public/products/show.html.erb
- app/views/public/registrations/new.html.erb
- app/views/public/sessions/new.html.erb
> [add]商品一覧・詳細修正・会員ログイン画面レイアウト調整中

- app/controllers/admin/genres_controller.rb
- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
> [add]ジャンル編集 機能追加

- app/controllers/admin/customers_controller.rb
- app/views/admin/customers/edit.html.erb
- app/views/admin/customers/index.html.erb
- app/views/admin/customers/show.html.erb
admin/customersのshowとeditページ更新しました
> [add]editページ更新しました

- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
> [add]ジャンル編集 レイアウト変更

- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
- app/views/public/homes/top.html.erb
> Public homes

- app/views/layouts/application.html.erb
- app/views/public/homes/about.html.erb
> [add]top,about,header追加

- Gemfile
- Gemfile.lock
- app/controllers/public/customers_controller.rb
- app/views/admin/customers/edit.html.erb
- app/views/admin/customers/index.html.erb
- app/views/admin/customers/show.html.erb
- app/views/kaminari/_first_page.html.erb
- app/views/kaminari/_gap.html.erb
- app/views/kaminari/_last_page.html.erb
- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_page.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/kaminari/_prev_page.html.erb
- config/initializers/kaminari_config.rb
- config/routes.rb
customersのビューいじりました。kaminari追加しました。
> [add]kaminari入れました

- app/controllers/application_controller.rb
- app/controllers/public/products_controller.rb
- app/models/cart_product.rb
- app/models/customer.rb
- app/models/product.rb
- app/views/admin/sessions/new.html.erb
- app/views/public/products/show.html.erb
- config/routes.rb
> [update]routes,public_product

- app/controllers/admin/products_controller.rb
- app/models/genre.rb
- app/views/admin/products/edit.html.erb
- app/views/admin/products/index.html.erb
- app/views/admin/products/new.html.erb
- app/views/admin/products/show.html.erb
admin/productsにジャンルとステータスを作成しました。
> [add]admin/products genre status

- app/models/product.rb
- app/views/public/products/index.html.erb
- app/views/public/products/show.html.erb
> [fix]商品一覧・詳細修正

- app/controllers/application_controller.rb
- app/views/layouts/_customer_header.html.erb
- app/views/layouts/_login_customer_header.html.erb
- app/views/layouts/application.html.erb
> [add]トップページ編集

- app/controllers/public/orders_controller.rb
- app/views/admin/customers/edit.html.erb
- app/views/public/orders/new.html.erb
> [add]order/new編集

- app/models/admin.rb
- db/seeds.rb
> [add]管理者用アカウント追加

- app/controllers/public/orders_controller.rb
- app/models/shipping_address.rb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/new.html.erb
- config/routes.rb
[add]public/orders confirm画面　追加しました。
> [add]public/orders confirm画面

- app/controllers/public/cart_products_controller.rb
- app/views/public/cart_products/_cart_products.html.erb
- app/views/public/cart_products/index.html.erb
- config/routes.rb
> [add]カート機能ビュー、コントローラー編集

- app/controllers/admin/homes_controller.rb
- app/controllers/public/products_controller.rb
- app/views/admin/homes/top.html.erb
- app/views/admin/products/show.html.erb
- app/views/layouts/_admin_header.html.erb
- app/views/public/products/index.html.erb
- app/views/public/products/show.html.erb
- config/routes.rb
ジャンル検索機能実装しました。
また、管理者用トップページ作成のブランチをマージしました。
> ジャンル検索機能実装

- app/controllers/public/cart_products_controller.rb
- app/views/public/products/show.html.erb
> [update]カート機能実装途中

- app/controllers/public/cart_products_controller.rb
- config/routes.rb
> [add]cart_productsコントローラー修正

- app/controllers/public/orders_controller.rb
- app/views/public/orders/confirm.html.erb
- config/routes.rb
[add]public/orders confirmとcomplete画面 追加しました。
> [add]public/orders confirmとcomplete画面

- app/controllers/public/customers_controller.rb
- app/views/public/customers/show.html.erb
- app/views/public/products/index.html.erb
- config/routes.rb
> [add]マイページ作成

- app/views/admin/customers/edit.html.erb
- app/views/admin/customers/index.html.erb
- app/views/admin/customers/show.html.erb
> [add]admin/customersちょっと変えました

- app/controllers/public/customers_controller.rb
- app/views/public/customers/edit.html.erb
> [add]マイページ・会員情報編集ページ追加

- app/controllers/admin/products_controller.rb
- app/views/admin/products/index.html.erb
- app/views/admin/products/new.html.erb
- config/initializers/kaminari_config.rb
[add]admin/products pagenation 追加しました
> [add]admin/products pagenation

- app/views/admin/products/edit.html.erb
- app/views/admin/products/index.html.erb
- app/views/admin/products/new.html.erb
- app/views/admin/products/show.html.erb
- app/views/layouts/_errors.html.erb
[fix]admin/products [add]layouts/errorsエラーメッセージ
> [fix]admin/products [add]layouts/errorsエラーメッセージ

- app/controllers/admin/customers_controller.rb
- app/controllers/public/sessions_controller.rb
- app/views/admin/customers/edit.html.erb
- app/views/admin/customers/index.html.erb
> [add]退会した人をログインできないようにしました

- app/controllers/admin/sessions_controller.rb
[add]admin/order ログイン前後 遷移を追加しました
> [add]admin/order ログイン前後

- app/assets/stylesheets/public/shipping_addresses.scss
- app/assets/stylesheets/shipping_addresses.scss
- app/controllers/public/cart_products_controller.rb
- app/controllers/public/shipping_addresses_controller.rb
- app/helpers/public/shipping_addresses_helper.rb
- app/helpers/shipping_addresses_helper.rb
- app/models/cart_product.rb
- app/models/product.rb
- app/views/public/cart_products/_cart_products.html.erb
- test/controllers/public/shipping_addresses_controller_test.rb
- test/controllers/shipping_addresses_controller_test.rb
> [add]コントローラー追加

- app/controllers/admin/homes_controller.rb
- app/controllers/admin/orders_controller.rb
- app/views/admin/homes/top.html.erb
- app/views/admin/orders/show.html.erb
[add]admin/orders show画面 ざっくり追加しました。
> [add]admin/orders show画面

- app/controllers/admin/orders_controller.rb
- app/models/product.rb
- app/views/admin/homes/top.html.erb
- app/views/admin/orders/show.html.erb
[add]admin/order view 変更しました
admin/topも日時表示変更
> [add]admin/order view

- app/controllers/public/homes_controller.rb
- app/views/layouts/application.html.erb
- app/views/public/cart_products/_cart_products.html.erb
- app/views/public/homes/top.html.erb
> [add]ジャンル検索追加

- app/views/public/customers/show.html.erb
- app/views/public/homes/top.html.erb
- app/views/public/products/index.html.erb
> [update]public_customers

- app/controllers/admin/customers_controller.rb
- app/controllers/public/customers_controller.rb
- app/views/public/registrations/new.html.erb
> [add]新規登録画面整えました

- app/controllers/admin/orders_controller.rb
- app/controllers/admin/products_controller.rb
- app/models/product.rb
- app/views/admin/orders/show.html.erb
> [add]admin/order ステータス

- app/controllers/public/cart_products_controller.rb
- app/views/public/customers/edit.html.erb
- app/views/public/products/show.html.erb
> [update]商品詳細ページ

- app/views/public/homes/top.html.erb
- app/views/public/products/index.html.erb
> [update]商品一覧

- app/controllers/public/orders_controller.rb
- app/models/order_product.rb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/new.html.erb
[add]public/orders hidden_field　追加しました
> [add]public/orders hidden_field

- app/controllers/public/homes_controller.rb
- app/controllers/public/products_controller.rb
商品一覧・ジャンル検索機能をis_active=trueの商品のみ表示されるよう修正いたしました。
> [update]販売中商品のみ表示

- app/controllers/public/orders_controller.rb
- app/views/admin/homes/top.html.erb
- app/views/public/orders/confirm.html.erb
[add]admin/order create機能 追加しました
> [add]admin/order create機能

- app/views/layouts/_footer.html.erb
- app/views/layouts/application.html.erb
> [add]フッター編集

- app/controllers/admin/homes_controller.rb
- app/controllers/admin/orders_controller.rb
- app/controllers/public/orders_controller.rb
- app/models/order.rb
- app/models/order_product.rb
- app/views/admin/homes/top.html.erb
- app/views/admin/orders/show.html.erb
- app/views/public/orders/confirm.html.erb
- config/locales/ja.yml
> [add]admin/order show画面とステータス

- app/views/admin/orders/show.html.erb
[fix]ルーティングエラーのためみさのデータをpullすることにしました
> [fix]ルーティング？

- app/javascript/packs/application.js
> [edit]application.js編集

- app/javascript/packs/application.js
- app/views/admin/customers/edit.html.erb
- app/views/admin/customers/index.html.erb
- app/views/admin/customers/show.html.erb
- app/views/public/orders/new.html.erb
> [add]fontawesome使えるようにしました

- app/controllers/public/products_controller.rb
- app/views/public/customers/edit.html.erb
- app/views/public/customers/show.html.erb
- app/views/public/customers/unsubscribe.html.erb
- app/views/public/products/index.html.erb
- app/views/public/products/show.html.erb
> [fix]商品詳細ページ

- app/controllers/admin/homes_controller.rb
- app/controllers/admin/orders_controller.rb
- app/views/admin/homes/top.html.erb
- app/views/admin/orders/show.html.erb
- config/locales/ja.yml
> [add]admin/order編集しました

- app/controllers/public/orders_controller.rb
- app/views/public/homes/top.html.erb
- app/views/public/orders/index.html.erb
- app/views/public/orders/show.html.erb
> [add]注文履歴・詳細追加

- app/views/layouts/_admin_header.html.erb
- app/views/layouts/_customer_header.html.erb
- app/views/layouts/_footer.html.erb
- app/views/layouts/_login_customer_header.html.erb
- app/views/layouts/application.html.erb
- app/views/public/homes/about.html.erb
- app/views/public/homes/top.html.erb
レイアウト　ヘッダー、フッタ、 topページ完成　aboutページ途中
> [edit]レイアウト　ヘッダー、フッタ、 topページ完成　aboutページ途中

- app/assets/stylesheets/public/searches.scss
- app/controllers/public/searches_controller.rb
- app/helpers/public/searches_helper.rb
- config/routes.rb
- test/controllers/public/searches_controller_test.rb
search機能　
ルーティング編集、コントローラー、ビュー追加
> [add]saerch機能追加

- app/views/public/orders/index.html.erb
- app/views/public/orders/show.html.erb
> [update]注文履歴レイアウト調整

- app/controllers/public/orders_controller.rb
> [fix]orderコントローラー修正

- app/controllers/public/searches_controller.rb
- app/views/layouts/_customer_header.html.erb
- app/views/layouts/_login_customer_header.html.erb
- app/views/public/searches/_search.html.erb
- app/views/public/searches/search.html.erb
> [edit]ヘッダーに検索欄追加　まだ使えません

- app/views/public/cart_products/_cart_products.html.erb
- app/views/public/cart_products/index.html.erb
[edit]cart_product編集　バリテーション、金額のカンマ
> [edit]cart_product編集　バリテーション、金額のカンマ

- app/views/public/customers/unsubscribe.html.erb
- app/views/public/orders/index.html.erb
- app/views/public/products/_genre.html.erb
- app/views/public/products/index.html.erb
- app/views/public/products/index.js.erb
> [update]レイアウト調整

- app/controllers/admin/order_products_controller.rb
- app/controllers/admin/orders_controller.rb
- app/views/layouts/application.html.erb
> [add]制作ステータス連動

- app/controllers/admin/customers_controller.rb
- app/controllers/admin/genres_controller.rb
- app/controllers/admin/homes_controller.rb
- app/controllers/admin/order_products_controller.rb
- app/controllers/admin/orders_controller.rb
- app/controllers/admin/products_controller.rb
- app/views/admin/homes/top.html.erb
[fix]admin/orderコントローラ　 [add]adminログイン認証
> [fix]admin/orderコントローラ　 [add]adminログイン認証

- app/models/product.rb
- config/locales/devise.en.yml
> [add] productモデル修正

- app/controllers/public/searches_controller.rb
- app/views/public/searches/search.html.erb
> [edit]serachビュー編集

- app/controllers/public/searches_controller.rb
- app/models/product.rb
- app/views/public/searches/_search.html.erb
- app/views/public/searches/search.html.erb
> [edit]検索機能(完了)

- app/views/admin/genres/_index.html.erb
- app/views/admin/orders/show.html.erb
- app/views/public/shipping_addresses/edit.html.erb
- config/locales/devise.ja.yml
- config/locales/ja.yml
[add]エラーメッセージ日本語化 [fix]shippingaddress一覧
> [add]エラーメッセージ日本語化 [fix]shippingaddress一覧

- app/controllers/admin/genres_controller.rb
- app/views/admin/genres/_index.html.erb
- app/views/admin/genres/destroy.js.erb
- app/views/admin/orders/show.html.erb
- app/views/public/customers/show.html.erb
- app/views/public/homes/top.html.erb
- app/views/public/orders/index.html.erb
- app/views/public/products/show.html.erb
- app/views/public/shipping_addresses/index.html.erb
> [update]ジャンル削除機能削除・レイアウト調整

- app/views/public/orders/index.html.erb
- app/views/public/orders/show.html.erb
- app/views/public/shipping_addresses/edit.html.erb
> [complete]
